// Dados mockados para demonstração da plataforma TAOS

import { OrdemServico, Metricas, Tecnico, Territorio, Usuario } from './types';

export const mockUsuario: Usuario = {
  id: '1',
  nome: 'João Silva',
  email: 'joao.silva@isp.com.br',
  perfil: 'noc',
};

export const mockMetricas: Metricas = {
  total_os: 47,
  resolvidas_remoto: 18,
  despachadas: 22,
  em_andamento: 7,
  concluidas_hoje: 31,
  tempo_medio_solucao: 45,
  taxa_retorno: 8.5,
  sla_cumprido: 94.2,
};

export const mockTecnicos: Tecnico[] = [
  {
    id: 't1',
    nome: 'Carlos Mendes',
    status: 'busy',
    localizacao: { lat: -23.5505, lng: -46.6333 },
    habilidades: ['fibra', 'roteador', 'onu'],
    fila_atual: 3,
    territorio: 'zona_norte',
  },
  {
    id: 't2',
    nome: 'Ana Paula',
    status: 'available',
    localizacao: { lat: -23.5489, lng: -46.6388 },
    habilidades: ['fibra', 'wifi', 'cabeamento'],
    fila_atual: 1,
    territorio: 'zona_norte',
  },
  {
    id: 't3',
    nome: 'Roberto Lima',
    status: 'busy',
    localizacao: { lat: -23.5629, lng: -46.6544 },
    habilidades: ['fibra', 'onu', 'olt'],
    fila_atual: 4,
    territorio: 'centro',
  },
  {
    id: 't4',
    nome: 'Mariana Costa',
    status: 'available',
    localizacao: { lat: -23.5733, lng: -46.6417 },
    habilidades: ['wifi', 'roteador', 'cabeamento'],
    fila_atual: 0,
    territorio: 'zona_sul',
  },
];

export const mockTerritorios: Territorio[] = [
  {
    id: 'zona_norte',
    nome: 'Zona Norte',
    bairros: ['Santana', 'Tucuruvi', 'Vila Maria'],
    tecnicos: ['t1', 't2'],
    cor: '#3B82F6',
  },
  {
    id: 'centro',
    nome: 'Centro',
    bairros: ['Sé', 'República', 'Consolação'],
    tecnicos: ['t3'],
    cor: '#10B981',
  },
  {
    id: 'zona_sul',
    nome: 'Zona Sul',
    bairros: ['Vila Mariana', 'Saúde', 'Jabaquara'],
    tecnicos: ['t4'],
    cor: '#F59E0B',
  },
];

export const mockOrdensServico: OrdemServico[] = [
  {
    id: 'os1',
    numero_os: 'OS-2024-001234',
    cliente: {
      id: 'c1',
      nome: 'Maria Santos',
      contrato: 'CT-45678',
      endereco: 'Rua das Flores, 123',
      bairro: 'Santana',
      cidade: 'São Paulo',
      telefone: '(11) 98765-4321',
      plano: 'Fibra 500MB',
      pop: 'POP-Santana',
    },
    status: 'diagnosing',
    prioridade: 'high',
    problema_relatado: 'Cliente sem internet desde ontem à noite',
    problema_tipo: 'no_internet',
    data_abertura: new Date('2024-01-15T08:30:00'),
    sla_expira_em: new Date('2024-01-15T16:30:00'),
    observacoes: ['Cliente já reiniciou equipamento', 'Verificar ONU'],
    origem: 'ixc',
  },
  {
    id: 'os2',
    numero_os: 'OS-2024-001235',
    cliente: {
      id: 'c2',
      nome: 'João Oliveira',
      contrato: 'CT-45679',
      endereco: 'Av. Paulista, 1000',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      telefone: '(11) 97654-3210',
      plano: 'Fibra 300MB',
      pop: 'POP-Centro',
    },
    status: 'dispatched',
    prioridade: 'medium',
    problema_relatado: 'Internet lenta, não atinge velocidade contratada',
    problema_tipo: 'slow',
    tecnico_atribuido: mockTecnicos[2],
    data_abertura: new Date('2024-01-15T09:15:00'),
    data_agendamento: new Date('2024-01-15T14:00:00'),
    sla_expira_em: new Date('2024-01-15T21:15:00'),
    observacoes: ['Teste de velocidade: 50MB', 'Possível problema na ONU'],
    origem: 'ixc',
  },
  {
    id: 'os3',
    numero_os: 'OS-2024-001236',
    cliente: {
      id: 'c3',
      nome: 'Pedro Costa',
      contrato: 'CT-45680',
      endereco: 'Rua Augusta, 500',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      telefone: '(11) 96543-2109',
      plano: 'Fibra 200MB',
      pop: 'POP-Centro',
    },
    status: 'resolved_remote',
    prioridade: 'low',
    problema_relatado: 'Wi-Fi não conecta no quarto',
    problema_tipo: 'wifi',
    data_abertura: new Date('2024-01-15T07:45:00'),
    data_conclusao: new Date('2024-01-15T08:15:00'),
    sla_expira_em: new Date('2024-01-16T07:45:00'),
    observacoes: [
      'Diagnóstico: sinal Wi-Fi fraco',
      'Orientado reposicionamento do roteador',
      'Cliente confirmou resolução',
    ],
    origem: 'ixc',
  },
  {
    id: 'os4',
    numero_os: 'OS-2024-001237',
    cliente: {
      id: 'c4',
      nome: 'Ana Silva',
      contrato: 'CT-45681',
      endereco: 'Rua Vergueiro, 2000',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      telefone: '(11) 95432-1098',
      plano: 'Fibra 400MB',
      pop: 'POP-Sul',
    },
    status: 'in_progress',
    prioridade: 'high',
    problema_relatado: 'Quedas constantes de conexão',
    problema_tipo: 'intermittent',
    tecnico_atribuido: mockTecnicos[3],
    data_abertura: new Date('2024-01-15T10:00:00'),
    data_agendamento: new Date('2024-01-15T11:30:00'),
    sla_expira_em: new Date('2024-01-15T18:00:00'),
    observacoes: ['Técnico a caminho', 'ETA: 15 minutos'],
    origem: 'ixc',
  },
  {
    id: 'os5',
    numero_os: 'OS-2024-001238',
    cliente: {
      id: 'c5',
      nome: 'Carlos Ferreira',
      contrato: 'CT-45682',
      endereco: 'Rua Tucuruvi, 800',
      bairro: 'Tucuruvi',
      cidade: 'São Paulo',
      telefone: '(11) 94321-0987',
      plano: 'Fibra 600MB',
      pop: 'POP-Santana',
    },
    status: 'pending',
    prioridade: 'medium',
    problema_relatado: 'Não consegue acessar alguns sites',
    problema_tipo: 'auth',
    data_abertura: new Date('2024-01-15T10:30:00'),
    sla_expira_em: new Date('2024-01-15T22:30:00'),
    observacoes: ['Aguardando diagnóstico automático'],
    origem: 'ixc',
  },
  {
    id: 'os6',
    numero_os: 'OS-2024-001239',
    cliente: {
      id: 'c6',
      nome: 'Juliana Alves',
      contrato: 'CT-45683',
      endereco: 'Av. Jabaquara, 1500',
      bairro: 'Jabaquara',
      cidade: 'São Paulo',
      telefone: '(11) 93210-9876',
      plano: 'Fibra 300MB',
      pop: 'POP-Sul',
    },
    status: 'completed',
    prioridade: 'low',
    problema_relatado: 'Dúvida sobre instalação de segundo roteador',
    problema_tipo: 'wifi',
    data_abertura: new Date('2024-01-14T15:00:00'),
    data_conclusao: new Date('2024-01-14T16:30:00'),
    sla_expira_em: new Date('2024-01-15T15:00:00'),
    observacoes: ['Orientação remota realizada', 'Cliente satisfeito'],
    origem: 'ixc',
  },
];
